#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_PHONG_TRO")]
	public partial class dbQuanLyNhaTroDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTPHIEUTHU(CTPHIEUTHU instance);
    partial void UpdateCTPHIEUTHU(CTPHIEUTHU instance);
    partial void DeleteCTPHIEUTHU(CTPHIEUTHU instance);
    partial void InsertCTTHIETBI(CTTHIETBI instance);
    partial void UpdateCTTHIETBI(CTTHIETBI instance);
    partial void DeleteCTTHIETBI(CTTHIETBI instance);
    partial void InsertDICHVU(DICHVU instance);
    partial void UpdateDICHVU(DICHVU instance);
    partial void DeleteDICHVU(DICHVU instance);
    partial void InsertLOAIPHONG(LOAIPHONG instance);
    partial void UpdateLOAIPHONG(LOAIPHONG instance);
    partial void DeleteLOAIPHONG(LOAIPHONG instance);
    partial void InsertKHACHTRO(KHACHTRO instance);
    partial void UpdateKHACHTRO(KHACHTRO instance);
    partial void DeleteKHACHTRO(KHACHTRO instance);
    partial void InsertPHIEUTHUEPHONG(PHIEUTHUEPHONG instance);
    partial void UpdatePHIEUTHUEPHONG(PHIEUTHUEPHONG instance);
    partial void DeletePHIEUTHUEPHONG(PHIEUTHUEPHONG instance);
    partial void InsertPHIEUTHUTIEN(PHIEUTHUTIEN instance);
    partial void UpdatePHIEUTHUTIEN(PHIEUTHUTIEN instance);
    partial void DeletePHIEUTHUTIEN(PHIEUTHUTIEN instance);
    partial void InsertPHONGTRO(PHONGTRO instance);
    partial void UpdatePHONGTRO(PHONGTRO instance);
    partial void DeletePHONGTRO(PHONGTRO instance);
    partial void InsertTHIETBI(THIETBI instance);
    partial void UpdateTHIETBI(THIETBI instance);
    partial void DeleteTHIETBI(THIETBI instance);
    #endregion
		
		public dbQuanLyNhaTroDataContext() : 
				base(global::BLL_DAL.Properties.Settings.Default.QL_PHONG_TROConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyNhaTroDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyNhaTroDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyNhaTroDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyNhaTroDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTPHIEUTHU> CTPHIEUTHUs
		{
			get
			{
				return this.GetTable<CTPHIEUTHU>();
			}
		}
		
		public System.Data.Linq.Table<CTTHIETBI> CTTHIETBIs
		{
			get
			{
				return this.GetTable<CTTHIETBI>();
			}
		}
		
		public System.Data.Linq.Table<DICHVU> DICHVUs
		{
			get
			{
				return this.GetTable<DICHVU>();
			}
		}
		
		public System.Data.Linq.Table<LOAIPHONG> LOAIPHONGs
		{
			get
			{
				return this.GetTable<LOAIPHONG>();
			}
		}
		
		public System.Data.Linq.Table<KHACHTRO> KHACHTROs
		{
			get
			{
				return this.GetTable<KHACHTRO>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTHUEPHONG> PHIEUTHUEPHONGs
		{
			get
			{
				return this.GetTable<PHIEUTHUEPHONG>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTHUTIEN> PHIEUTHUTIENs
		{
			get
			{
				return this.GetTable<PHIEUTHUTIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHONGTRO> PHONGTROs
		{
			get
			{
				return this.GetTable<PHONGTRO>();
			}
		}
		
		public System.Data.Linq.Table<THIETBI> THIETBIs
		{
			get
			{
				return this.GetTable<THIETBI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPHIEUTHU")]
	public partial class CTPHIEUTHU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CTPT;
		
		private int _MATHU;
		
		private int _MADV;
		
		private System.Nullable<double> _CHISOCU;
		
		private System.Nullable<double> _CHISOMOI;
		
		private System.Nullable<int> _THANHTIEN;
		
		private EntityRef<DICHVU> _DICHVU;
		
		private EntityRef<PHIEUTHUTIEN> _PHIEUTHUTIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CTPTChanging(int value);
    partial void OnID_CTPTChanged();
    partial void OnMATHUChanging(int value);
    partial void OnMATHUChanged();
    partial void OnMADVChanging(int value);
    partial void OnMADVChanged();
    partial void OnCHISOCUChanging(System.Nullable<double> value);
    partial void OnCHISOCUChanged();
    partial void OnCHISOMOIChanging(System.Nullable<double> value);
    partial void OnCHISOMOIChanged();
    partial void OnTHANHTIENChanging(System.Nullable<int> value);
    partial void OnTHANHTIENChanged();
    #endregion
		
		public CTPHIEUTHU()
		{
			this._DICHVU = default(EntityRef<DICHVU>);
			this._PHIEUTHUTIEN = default(EntityRef<PHIEUTHUTIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CTPT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CTPT
		{
			get
			{
				return this._ID_CTPT;
			}
			set
			{
				if ((this._ID_CTPT != value))
				{
					this.OnID_CTPTChanging(value);
					this.SendPropertyChanging();
					this._ID_CTPT = value;
					this.SendPropertyChanged("ID_CTPT");
					this.OnID_CTPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHU", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MATHU
		{
			get
			{
				return this._MATHU;
			}
			set
			{
				if ((this._MATHU != value))
				{
					if (this._PHIEUTHUTIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHUChanging(value);
					this.SendPropertyChanging();
					this._MATHU = value;
					this.SendPropertyChanged("MATHU");
					this.OnMATHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MADV
		{
			get
			{
				return this._MADV;
			}
			set
			{
				if ((this._MADV != value))
				{
					if (this._DICHVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADVChanging(value);
					this.SendPropertyChanging();
					this._MADV = value;
					this.SendPropertyChanged("MADV");
					this.OnMADVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHISOCU", DbType="Float")]
		public System.Nullable<double> CHISOCU
		{
			get
			{
				return this._CHISOCU;
			}
			set
			{
				if ((this._CHISOCU != value))
				{
					this.OnCHISOCUChanging(value);
					this.SendPropertyChanging();
					this._CHISOCU = value;
					this.SendPropertyChanged("CHISOCU");
					this.OnCHISOCUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHISOMOI", DbType="Float")]
		public System.Nullable<double> CHISOMOI
		{
			get
			{
				return this._CHISOMOI;
			}
			set
			{
				if ((this._CHISOMOI != value))
				{
					this.OnCHISOMOIChanging(value);
					this.SendPropertyChanging();
					this._CHISOMOI = value;
					this.SendPropertyChanged("CHISOMOI");
					this.OnCHISOMOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Int")]
		public System.Nullable<int> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICHVU_CTPHIEUTHU", Storage="_DICHVU", ThisKey="MADV", OtherKey="MADV", IsForeignKey=true)]
		public DICHVU DICHVU
		{
			get
			{
				return this._DICHVU.Entity;
			}
			set
			{
				DICHVU previousValue = this._DICHVU.Entity;
				if (((previousValue != value) 
							|| (this._DICHVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DICHVU.Entity = null;
						previousValue.CTPHIEUTHUs.Remove(this);
					}
					this._DICHVU.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUTHUs.Add(this);
						this._MADV = value.MADV;
					}
					else
					{
						this._MADV = default(int);
					}
					this.SendPropertyChanged("DICHVU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUTHUTIEN_CTPHIEUTHU", Storage="_PHIEUTHUTIEN", ThisKey="MATHU", OtherKey="MATHU", IsForeignKey=true)]
		public PHIEUTHUTIEN PHIEUTHUTIEN
		{
			get
			{
				return this._PHIEUTHUTIEN.Entity;
			}
			set
			{
				PHIEUTHUTIEN previousValue = this._PHIEUTHUTIEN.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUTHUTIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUTHUTIEN.Entity = null;
						previousValue.CTPHIEUTHUs.Remove(this);
					}
					this._PHIEUTHUTIEN.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUTHUs.Add(this);
						this._MATHU = value.MATHU;
					}
					else
					{
						this._MATHU = default(int);
					}
					this.SendPropertyChanged("PHIEUTHUTIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTTHIETBI")]
	public partial class CTTHIETBI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPT;
		
		private int _MATB;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _TINHTRANG;
		
		private EntityRef<PHONGTRO> _PHONGTRO;
		
		private EntityRef<THIETBI> _THIETBI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPTChanging(int value);
    partial void OnMAPTChanged();
    partial void OnMATBChanging(int value);
    partial void OnMATBChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnTINHTRANGChanging(string value);
    partial void OnTINHTRANGChanged();
    #endregion
		
		public CTTHIETBI()
		{
			this._PHONGTRO = default(EntityRef<PHONGTRO>);
			this._THIETBI = default(EntityRef<THIETBI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAPT
		{
			get
			{
				return this._MAPT;
			}
			set
			{
				if ((this._MAPT != value))
				{
					if (this._PHONGTRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPTChanging(value);
					this.SendPropertyChanging();
					this._MAPT = value;
					this.SendPropertyChanged("MAPT");
					this.OnMAPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATB", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MATB
		{
			get
			{
				return this._MATB;
			}
			set
			{
				if ((this._MATB != value))
				{
					if (this._THIETBI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATBChanging(value);
					this.SendPropertyChanging();
					this._MATB = value;
					this.SendPropertyChanged("MATB");
					this.OnMATBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="NVarChar(50)")]
		public string TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGTRO_CTTHIETBI", Storage="_PHONGTRO", ThisKey="MAPT", OtherKey="MAPT", IsForeignKey=true)]
		public PHONGTRO PHONGTRO
		{
			get
			{
				return this._PHONGTRO.Entity;
			}
			set
			{
				PHONGTRO previousValue = this._PHONGTRO.Entity;
				if (((previousValue != value) 
							|| (this._PHONGTRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGTRO.Entity = null;
						previousValue.CTTHIETBIs.Remove(this);
					}
					this._PHONGTRO.Entity = value;
					if ((value != null))
					{
						value.CTTHIETBIs.Add(this);
						this._MAPT = value.MAPT;
					}
					else
					{
						this._MAPT = default(int);
					}
					this.SendPropertyChanged("PHONGTRO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THIETBI_CTTHIETBI", Storage="_THIETBI", ThisKey="MATB", OtherKey="MATB", IsForeignKey=true)]
		public THIETBI THIETBI
		{
			get
			{
				return this._THIETBI.Entity;
			}
			set
			{
				THIETBI previousValue = this._THIETBI.Entity;
				if (((previousValue != value) 
							|| (this._THIETBI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THIETBI.Entity = null;
						previousValue.CTTHIETBIs.Remove(this);
					}
					this._THIETBI.Entity = value;
					if ((value != null))
					{
						value.CTTHIETBIs.Add(this);
						this._MATB = value.MATB;
					}
					else
					{
						this._MATB = default(int);
					}
					this.SendPropertyChanged("THIETBI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DICHVU")]
	public partial class DICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADV;
		
		private string _TENDV;
		
		private System.Nullable<int> _DONGIA;
		
		private string _DONVITINH;
		
		private string _TRANGTHAI;
		
		private EntitySet<CTPHIEUTHU> _CTPHIEUTHUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADVChanging(int value);
    partial void OnMADVChanged();
    partial void OnTENDVChanging(string value);
    partial void OnTENDVChanged();
    partial void OnDONGIAChanging(System.Nullable<int> value);
    partial void OnDONGIAChanged();
    partial void OnDONVITINHChanging(string value);
    partial void OnDONVITINHChanged();
    partial void OnTRANGTHAIChanging(string value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public DICHVU()
		{
			this._CTPHIEUTHUs = new EntitySet<CTPHIEUTHU>(new Action<CTPHIEUTHU>(this.attach_CTPHIEUTHUs), new Action<CTPHIEUTHU>(this.detach_CTPHIEUTHUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MADV
		{
			get
			{
				return this._MADV;
			}
			set
			{
				if ((this._MADV != value))
				{
					this.OnMADVChanging(value);
					this.SendPropertyChanging();
					this._MADV = value;
					this.SendPropertyChanged("MADV");
					this.OnMADVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDV", DbType="NVarChar(50)")]
		public string TENDV
		{
			get
			{
				return this._TENDV;
			}
			set
			{
				if ((this._TENDV != value))
				{
					this.OnTENDVChanging(value);
					this.SendPropertyChanging();
					this._TENDV = value;
					this.SendPropertyChanged("TENDV");
					this.OnTENDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Int")]
		public System.Nullable<int> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONVITINH", DbType="NVarChar(50)")]
		public string DONVITINH
		{
			get
			{
				return this._DONVITINH;
			}
			set
			{
				if ((this._DONVITINH != value))
				{
					this.OnDONVITINHChanging(value);
					this.SendPropertyChanging();
					this._DONVITINH = value;
					this.SendPropertyChanged("DONVITINH");
					this.OnDONVITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="NVarChar(50)")]
		public string TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICHVU_CTPHIEUTHU", Storage="_CTPHIEUTHUs", ThisKey="MADV", OtherKey="MADV")]
		public EntitySet<CTPHIEUTHU> CTPHIEUTHUs
		{
			get
			{
				return this._CTPHIEUTHUs;
			}
			set
			{
				this._CTPHIEUTHUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPHIEUTHUs(CTPHIEUTHU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = this;
		}
		
		private void detach_CTPHIEUTHUs(CTPHIEUTHU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIPHONG")]
	public partial class LOAIPHONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALP;
		
		private string _TENLOAIPHONG;
		
		private System.Nullable<int> _DONGIA;
		
		private EntitySet<PHONGTRO> _PHONGTROs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALPChanging(int value);
    partial void OnMALPChanged();
    partial void OnTENLOAIPHONGChanging(string value);
    partial void OnTENLOAIPHONGChanged();
    partial void OnDONGIAChanging(System.Nullable<int> value);
    partial void OnDONGIAChanged();
    #endregion
		
		public LOAIPHONG()
		{
			this._PHONGTROs = new EntitySet<PHONGTRO>(new Action<PHONGTRO>(this.attach_PHONGTROs), new Action<PHONGTRO>(this.detach_PHONGTROs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MALP
		{
			get
			{
				return this._MALP;
			}
			set
			{
				if ((this._MALP != value))
				{
					this.OnMALPChanging(value);
					this.SendPropertyChanging();
					this._MALP = value;
					this.SendPropertyChanged("MALP");
					this.OnMALPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAIPHONG", DbType="NVarChar(50)")]
		public string TENLOAIPHONG
		{
			get
			{
				return this._TENLOAIPHONG;
			}
			set
			{
				if ((this._TENLOAIPHONG != value))
				{
					this.OnTENLOAIPHONGChanging(value);
					this.SendPropertyChanging();
					this._TENLOAIPHONG = value;
					this.SendPropertyChanged("TENLOAIPHONG");
					this.OnTENLOAIPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Int")]
		public System.Nullable<int> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIPHONG_PHONGTRO", Storage="_PHONGTROs", ThisKey="MALP", OtherKey="MALP")]
		public EntitySet<PHONGTRO> PHONGTROs
		{
			get
			{
				return this._PHONGTROs;
			}
			set
			{
				this._PHONGTROs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHONGTROs(PHONGTRO entity)
		{
			this.SendPropertyChanging();
			entity.LOAIPHONG = this;
		}
		
		private void detach_PHONGTROs(PHONGTRO entity)
		{
			this.SendPropertyChanging();
			entity.LOAIPHONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHTRO")]
	public partial class KHACHTRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKT;
		
		private string _HOTEN;
		
		private string _CMND;
		
		private string _GIOITINH;
		
		private string _NGHENGHIEP;
		
		private string _DIACHI;
		
		private string _SDT;
		
		private string _HINH;
		
		private System.Nullable<bool> _CHUHO;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private EntitySet<PHIEUTHUEPHONG> _PHIEUTHUEPHONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKTChanging(int value);
    partial void OnMAKTChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNGHENGHIEPChanging(string value);
    partial void OnNGHENGHIEPChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnHINHChanging(string value);
    partial void OnHINHChanged();
    partial void OnCHUHOChanging(System.Nullable<bool> value);
    partial void OnCHUHOChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    #endregion
		
		public KHACHTRO()
		{
			this._PHIEUTHUEPHONGs = new EntitySet<PHIEUTHUEPHONG>(new Action<PHIEUTHUEPHONG>(this.attach_PHIEUTHUEPHONGs), new Action<PHIEUTHUEPHONG>(this.detach_PHIEUTHUEPHONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAKT
		{
			get
			{
				return this._MAKT;
			}
			set
			{
				if ((this._MAKT != value))
				{
					this.OnMAKTChanging(value);
					this.SendPropertyChanging();
					this._MAKT = value;
					this.SendPropertyChanged("MAKT");
					this.OnMAKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(50)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(50)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEP", DbType="NVarChar(50)")]
		public string NGHENGHIEP
		{
			get
			{
				return this._NGHENGHIEP;
			}
			set
			{
				if ((this._NGHENGHIEP != value))
				{
					this.OnNGHENGHIEPChanging(value);
					this.SendPropertyChanging();
					this._NGHENGHIEP = value;
					this.SendPropertyChanged("NGHENGHIEP");
					this.OnNGHENGHIEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH", DbType="NVarChar(50)")]
		public string HINH
		{
			get
			{
				return this._HINH;
			}
			set
			{
				if ((this._HINH != value))
				{
					this.OnHINHChanging(value);
					this.SendPropertyChanging();
					this._HINH = value;
					this.SendPropertyChanged("HINH");
					this.OnHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUHO", DbType="Bit")]
		public System.Nullable<bool> CHUHO
		{
			get
			{
				return this._CHUHO;
			}
			set
			{
				if ((this._CHUHO != value))
				{
					this.OnCHUHOChanging(value);
					this.SendPropertyChanging();
					this._CHUHO = value;
					this.SendPropertyChanged("CHUHO");
					this.OnCHUHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHTRO_PHIEUTHUEPHONG", Storage="_PHIEUTHUEPHONGs", ThisKey="MAKT", OtherKey="MAKT")]
		public EntitySet<PHIEUTHUEPHONG> PHIEUTHUEPHONGs
		{
			get
			{
				return this._PHIEUTHUEPHONGs;
			}
			set
			{
				this._PHIEUTHUEPHONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUTHUEPHONGs(PHIEUTHUEPHONG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHTRO = this;
		}
		
		private void detach_PHIEUTHUEPHONGs(PHIEUTHUEPHONG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHTRO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTHUEPHONG")]
	public partial class PHIEUTHUEPHONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPHIEUTHUE;
		
		private System.Nullable<int> _MAKT;
		
		private System.Nullable<int> _MAPT;
		
		private System.Nullable<System.DateTime> _NGAYTHUE;
		
		private System.Nullable<System.DateTime> _NGAYTRA;
		
		private string _TRANGTHAI;
		
		private EntitySet<PHIEUTHUTIEN> _PHIEUTHUTIENs;
		
		private EntityRef<KHACHTRO> _KHACHTRO;
		
		private EntityRef<PHONGTRO> _PHONGTRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUTHUEChanging(int value);
    partial void OnMAPHIEUTHUEChanged();
    partial void OnMAKTChanging(System.Nullable<int> value);
    partial void OnMAKTChanged();
    partial void OnMAPTChanging(System.Nullable<int> value);
    partial void OnMAPTChanged();
    partial void OnNGAYTHUEChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTHUEChanged();
    partial void OnNGAYTRAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTRAChanged();
    partial void OnTRANGTHAIChanging(string value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public PHIEUTHUEPHONG()
		{
			this._PHIEUTHUTIENs = new EntitySet<PHIEUTHUTIEN>(new Action<PHIEUTHUTIEN>(this.attach_PHIEUTHUTIENs), new Action<PHIEUTHUTIEN>(this.detach_PHIEUTHUTIENs));
			this._KHACHTRO = default(EntityRef<KHACHTRO>);
			this._PHONGTRO = default(EntityRef<PHONGTRO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUTHUE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEUTHUE
		{
			get
			{
				return this._MAPHIEUTHUE;
			}
			set
			{
				if ((this._MAPHIEUTHUE != value))
				{
					this.OnMAPHIEUTHUEChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUTHUE = value;
					this.SendPropertyChanged("MAPHIEUTHUE");
					this.OnMAPHIEUTHUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKT", DbType="Int")]
		public System.Nullable<int> MAKT
		{
			get
			{
				return this._MAKT;
			}
			set
			{
				if ((this._MAKT != value))
				{
					if (this._KHACHTRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKTChanging(value);
					this.SendPropertyChanging();
					this._MAKT = value;
					this.SendPropertyChanged("MAKT");
					this.OnMAKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPT", DbType="Int")]
		public System.Nullable<int> MAPT
		{
			get
			{
				return this._MAPT;
			}
			set
			{
				if ((this._MAPT != value))
				{
					if (this._PHONGTRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPTChanging(value);
					this.SendPropertyChanging();
					this._MAPT = value;
					this.SendPropertyChanged("MAPT");
					this.OnMAPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHUE", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTHUE
		{
			get
			{
				return this._NGAYTHUE;
			}
			set
			{
				if ((this._NGAYTHUE != value))
				{
					this.OnNGAYTHUEChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHUE = value;
					this.SendPropertyChanged("NGAYTHUE");
					this.OnNGAYTHUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTRA", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTRA
		{
			get
			{
				return this._NGAYTRA;
			}
			set
			{
				if ((this._NGAYTRA != value))
				{
					this.OnNGAYTRAChanging(value);
					this.SendPropertyChanging();
					this._NGAYTRA = value;
					this.SendPropertyChanged("NGAYTRA");
					this.OnNGAYTRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="NVarChar(50)")]
		public string TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUTHUEPHONG_PHIEUTHUTIEN", Storage="_PHIEUTHUTIENs", ThisKey="MAPHIEUTHUE", OtherKey="MAPHIEUTHUE")]
		public EntitySet<PHIEUTHUTIEN> PHIEUTHUTIENs
		{
			get
			{
				return this._PHIEUTHUTIENs;
			}
			set
			{
				this._PHIEUTHUTIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHTRO_PHIEUTHUEPHONG", Storage="_KHACHTRO", ThisKey="MAKT", OtherKey="MAKT", IsForeignKey=true)]
		public KHACHTRO KHACHTRO
		{
			get
			{
				return this._KHACHTRO.Entity;
			}
			set
			{
				KHACHTRO previousValue = this._KHACHTRO.Entity;
				if (((previousValue != value) 
							|| (this._KHACHTRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHTRO.Entity = null;
						previousValue.PHIEUTHUEPHONGs.Remove(this);
					}
					this._KHACHTRO.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHUEPHONGs.Add(this);
						this._MAKT = value.MAKT;
					}
					else
					{
						this._MAKT = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHACHTRO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGTRO_PHIEUTHUEPHONG", Storage="_PHONGTRO", ThisKey="MAPT", OtherKey="MAPT", IsForeignKey=true)]
		public PHONGTRO PHONGTRO
		{
			get
			{
				return this._PHONGTRO.Entity;
			}
			set
			{
				PHONGTRO previousValue = this._PHONGTRO.Entity;
				if (((previousValue != value) 
							|| (this._PHONGTRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGTRO.Entity = null;
						previousValue.PHIEUTHUEPHONGs.Remove(this);
					}
					this._PHONGTRO.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHUEPHONGs.Add(this);
						this._MAPT = value.MAPT;
					}
					else
					{
						this._MAPT = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHONGTRO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUTHUTIENs(PHIEUTHUTIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUTHUEPHONG = this;
		}
		
		private void detach_PHIEUTHUTIENs(PHIEUTHUTIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUTHUEPHONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTHUTIEN")]
	public partial class PHIEUTHUTIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATHU;
		
		private System.Nullable<int> _MAPHIEUTHUE;
		
		private System.Nullable<System.DateTime> _NGAYBATDAU;
		
		private System.Nullable<System.DateTime> _NGAYKETTHUC;
		
		private int _TONGTIEN;
		
		private System.Nullable<int> _DATTHANHTOAN;
		
		private EntitySet<CTPHIEUTHU> _CTPHIEUTHUs;
		
		private EntityRef<PHIEUTHUEPHONG> _PHIEUTHUEPHONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHUChanging(int value);
    partial void OnMATHUChanged();
    partial void OnMAPHIEUTHUEChanging(System.Nullable<int> value);
    partial void OnMAPHIEUTHUEChanged();
    partial void OnNGAYBATDAUChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYBATDAUChanged();
    partial void OnNGAYKETTHUCChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYKETTHUCChanged();
    partial void OnTONGTIENChanging(int value);
    partial void OnTONGTIENChanged();
    partial void OnDATTHANHTOANChanging(System.Nullable<int> value);
    partial void OnDATTHANHTOANChanged();
    #endregion
		
		public PHIEUTHUTIEN()
		{
			this._CTPHIEUTHUs = new EntitySet<CTPHIEUTHU>(new Action<CTPHIEUTHU>(this.attach_CTPHIEUTHUs), new Action<CTPHIEUTHU>(this.detach_CTPHIEUTHUs));
			this._PHIEUTHUEPHONG = default(EntityRef<PHIEUTHUEPHONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATHU
		{
			get
			{
				return this._MATHU;
			}
			set
			{
				if ((this._MATHU != value))
				{
					this.OnMATHUChanging(value);
					this.SendPropertyChanging();
					this._MATHU = value;
					this.SendPropertyChanged("MATHU");
					this.OnMATHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUTHUE", DbType="Int")]
		public System.Nullable<int> MAPHIEUTHUE
		{
			get
			{
				return this._MAPHIEUTHUE;
			}
			set
			{
				if ((this._MAPHIEUTHUE != value))
				{
					if (this._PHIEUTHUEPHONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHIEUTHUEChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUTHUE = value;
					this.SendPropertyChanged("MAPHIEUTHUE");
					this.OnMAPHIEUTHUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBATDAU", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYBATDAU
		{
			get
			{
				return this._NGAYBATDAU;
			}
			set
			{
				if ((this._NGAYBATDAU != value))
				{
					this.OnNGAYBATDAUChanging(value);
					this.SendPropertyChanging();
					this._NGAYBATDAU = value;
					this.SendPropertyChanged("NGAYBATDAU");
					this.OnNGAYBATDAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKETTHUC", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYKETTHUC
		{
			get
			{
				return this._NGAYKETTHUC;
			}
			set
			{
				if ((this._NGAYKETTHUC != value))
				{
					this.OnNGAYKETTHUCChanging(value);
					this.SendPropertyChanging();
					this._NGAYKETTHUC = value;
					this.SendPropertyChanged("NGAYKETTHUC");
					this.OnNGAYKETTHUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Int NOT NULL")]
		public int TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATTHANHTOAN", DbType="Int")]
		public System.Nullable<int> DATTHANHTOAN
		{
			get
			{
				return this._DATTHANHTOAN;
			}
			set
			{
				if ((this._DATTHANHTOAN != value))
				{
					this.OnDATTHANHTOANChanging(value);
					this.SendPropertyChanging();
					this._DATTHANHTOAN = value;
					this.SendPropertyChanged("DATTHANHTOAN");
					this.OnDATTHANHTOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUTHUTIEN_CTPHIEUTHU", Storage="_CTPHIEUTHUs", ThisKey="MATHU", OtherKey="MATHU")]
		public EntitySet<CTPHIEUTHU> CTPHIEUTHUs
		{
			get
			{
				return this._CTPHIEUTHUs;
			}
			set
			{
				this._CTPHIEUTHUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUTHUEPHONG_PHIEUTHUTIEN", Storage="_PHIEUTHUEPHONG", ThisKey="MAPHIEUTHUE", OtherKey="MAPHIEUTHUE", IsForeignKey=true)]
		public PHIEUTHUEPHONG PHIEUTHUEPHONG
		{
			get
			{
				return this._PHIEUTHUEPHONG.Entity;
			}
			set
			{
				PHIEUTHUEPHONG previousValue = this._PHIEUTHUEPHONG.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUTHUEPHONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUTHUEPHONG.Entity = null;
						previousValue.PHIEUTHUTIENs.Remove(this);
					}
					this._PHIEUTHUEPHONG.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHUTIENs.Add(this);
						this._MAPHIEUTHUE = value.MAPHIEUTHUE;
					}
					else
					{
						this._MAPHIEUTHUE = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHIEUTHUEPHONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPHIEUTHUs(CTPHIEUTHU entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUTHUTIEN = this;
		}
		
		private void detach_CTPHIEUTHUs(CTPHIEUTHU entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUTHUTIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGTRO")]
	public partial class PHONGTRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPT;
		
		private System.Nullable<int> _MALP;
		
		private string _TENPHONG;
		
		private System.Nullable<int> _SLTOIDA;
		
		private string _TRANGTHAI;
		
		private System.Nullable<int> _SONGUOIHIENTAI;
		
		private EntitySet<CTTHIETBI> _CTTHIETBIs;
		
		private EntitySet<PHIEUTHUEPHONG> _PHIEUTHUEPHONGs;
		
		private EntityRef<LOAIPHONG> _LOAIPHONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPTChanging(int value);
    partial void OnMAPTChanged();
    partial void OnMALPChanging(System.Nullable<int> value);
    partial void OnMALPChanged();
    partial void OnTENPHONGChanging(string value);
    partial void OnTENPHONGChanged();
    partial void OnSLTOIDAChanging(System.Nullable<int> value);
    partial void OnSLTOIDAChanged();
    partial void OnTRANGTHAIChanging(string value);
    partial void OnTRANGTHAIChanged();
    partial void OnSONGUOIHIENTAIChanging(System.Nullable<int> value);
    partial void OnSONGUOIHIENTAIChanged();
    #endregion
		
		public PHONGTRO()
		{
			this._CTTHIETBIs = new EntitySet<CTTHIETBI>(new Action<CTTHIETBI>(this.attach_CTTHIETBIs), new Action<CTTHIETBI>(this.detach_CTTHIETBIs));
			this._PHIEUTHUEPHONGs = new EntitySet<PHIEUTHUEPHONG>(new Action<PHIEUTHUEPHONG>(this.attach_PHIEUTHUEPHONGs), new Action<PHIEUTHUEPHONG>(this.detach_PHIEUTHUEPHONGs));
			this._LOAIPHONG = default(EntityRef<LOAIPHONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPT
		{
			get
			{
				return this._MAPT;
			}
			set
			{
				if ((this._MAPT != value))
				{
					this.OnMAPTChanging(value);
					this.SendPropertyChanging();
					this._MAPT = value;
					this.SendPropertyChanged("MAPT");
					this.OnMAPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALP", DbType="Int")]
		public System.Nullable<int> MALP
		{
			get
			{
				return this._MALP;
			}
			set
			{
				if ((this._MALP != value))
				{
					if (this._LOAIPHONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALPChanging(value);
					this.SendPropertyChanging();
					this._MALP = value;
					this.SendPropertyChanged("MALP");
					this.OnMALPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPHONG", DbType="NVarChar(50)")]
		public string TENPHONG
		{
			get
			{
				return this._TENPHONG;
			}
			set
			{
				if ((this._TENPHONG != value))
				{
					this.OnTENPHONGChanging(value);
					this.SendPropertyChanging();
					this._TENPHONG = value;
					this.SendPropertyChanged("TENPHONG");
					this.OnTENPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLTOIDA", DbType="Int")]
		public System.Nullable<int> SLTOIDA
		{
			get
			{
				return this._SLTOIDA;
			}
			set
			{
				if ((this._SLTOIDA != value))
				{
					this.OnSLTOIDAChanging(value);
					this.SendPropertyChanging();
					this._SLTOIDA = value;
					this.SendPropertyChanged("SLTOIDA");
					this.OnSLTOIDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="NVarChar(50)")]
		public string TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGUOIHIENTAI", DbType="Int")]
		public System.Nullable<int> SONGUOIHIENTAI
		{
			get
			{
				return this._SONGUOIHIENTAI;
			}
			set
			{
				if ((this._SONGUOIHIENTAI != value))
				{
					this.OnSONGUOIHIENTAIChanging(value);
					this.SendPropertyChanging();
					this._SONGUOIHIENTAI = value;
					this.SendPropertyChanged("SONGUOIHIENTAI");
					this.OnSONGUOIHIENTAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGTRO_CTTHIETBI", Storage="_CTTHIETBIs", ThisKey="MAPT", OtherKey="MAPT")]
		public EntitySet<CTTHIETBI> CTTHIETBIs
		{
			get
			{
				return this._CTTHIETBIs;
			}
			set
			{
				this._CTTHIETBIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGTRO_PHIEUTHUEPHONG", Storage="_PHIEUTHUEPHONGs", ThisKey="MAPT", OtherKey="MAPT")]
		public EntitySet<PHIEUTHUEPHONG> PHIEUTHUEPHONGs
		{
			get
			{
				return this._PHIEUTHUEPHONGs;
			}
			set
			{
				this._PHIEUTHUEPHONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIPHONG_PHONGTRO", Storage="_LOAIPHONG", ThisKey="MALP", OtherKey="MALP", IsForeignKey=true)]
		public LOAIPHONG LOAIPHONG
		{
			get
			{
				return this._LOAIPHONG.Entity;
			}
			set
			{
				LOAIPHONG previousValue = this._LOAIPHONG.Entity;
				if (((previousValue != value) 
							|| (this._LOAIPHONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIPHONG.Entity = null;
						previousValue.PHONGTROs.Remove(this);
					}
					this._LOAIPHONG.Entity = value;
					if ((value != null))
					{
						value.PHONGTROs.Add(this);
						this._MALP = value.MALP;
					}
					else
					{
						this._MALP = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAIPHONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTTHIETBIs(CTTHIETBI entity)
		{
			this.SendPropertyChanging();
			entity.PHONGTRO = this;
		}
		
		private void detach_CTTHIETBIs(CTTHIETBI entity)
		{
			this.SendPropertyChanging();
			entity.PHONGTRO = null;
		}
		
		private void attach_PHIEUTHUEPHONGs(PHIEUTHUEPHONG entity)
		{
			this.SendPropertyChanging();
			entity.PHONGTRO = this;
		}
		
		private void detach_PHIEUTHUEPHONGs(PHIEUTHUEPHONG entity)
		{
			this.SendPropertyChanging();
			entity.PHONGTRO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THIETBI")]
	public partial class THIETBI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATB;
		
		private string _TENTB;
		
		private string _NHANHIEU;
		
		private System.Nullable<int> _GIA;
		
		private EntitySet<CTTHIETBI> _CTTHIETBIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATBChanging(int value);
    partial void OnMATBChanged();
    partial void OnTENTBChanging(string value);
    partial void OnTENTBChanged();
    partial void OnNHANHIEUChanging(string value);
    partial void OnNHANHIEUChanged();
    partial void OnGIAChanging(System.Nullable<int> value);
    partial void OnGIAChanged();
    #endregion
		
		public THIETBI()
		{
			this._CTTHIETBIs = new EntitySet<CTTHIETBI>(new Action<CTTHIETBI>(this.attach_CTTHIETBIs), new Action<CTTHIETBI>(this.detach_CTTHIETBIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATB", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATB
		{
			get
			{
				return this._MATB;
			}
			set
			{
				if ((this._MATB != value))
				{
					this.OnMATBChanging(value);
					this.SendPropertyChanging();
					this._MATB = value;
					this.SendPropertyChanged("MATB");
					this.OnMATBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTB", DbType="NVarChar(50)")]
		public string TENTB
		{
			get
			{
				return this._TENTB;
			}
			set
			{
				if ((this._TENTB != value))
				{
					this.OnTENTBChanging(value);
					this.SendPropertyChanging();
					this._TENTB = value;
					this.SendPropertyChanged("TENTB");
					this.OnTENTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANHIEU", DbType="NVarChar(50)")]
		public string NHANHIEU
		{
			get
			{
				return this._NHANHIEU;
			}
			set
			{
				if ((this._NHANHIEU != value))
				{
					this.OnNHANHIEUChanging(value);
					this.SendPropertyChanging();
					this._NHANHIEU = value;
					this.SendPropertyChanged("NHANHIEU");
					this.OnNHANHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA", DbType="Int")]
		public System.Nullable<int> GIA
		{
			get
			{
				return this._GIA;
			}
			set
			{
				if ((this._GIA != value))
				{
					this.OnGIAChanging(value);
					this.SendPropertyChanging();
					this._GIA = value;
					this.SendPropertyChanged("GIA");
					this.OnGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THIETBI_CTTHIETBI", Storage="_CTTHIETBIs", ThisKey="MATB", OtherKey="MATB")]
		public EntitySet<CTTHIETBI> CTTHIETBIs
		{
			get
			{
				return this._CTTHIETBIs;
			}
			set
			{
				this._CTTHIETBIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTTHIETBIs(CTTHIETBI entity)
		{
			this.SendPropertyChanging();
			entity.THIETBI = this;
		}
		
		private void detach_CTTHIETBIs(CTTHIETBI entity)
		{
			this.SendPropertyChanging();
			entity.THIETBI = null;
		}
	}
}
#pragma warning restore 1591
